config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :stages
  devise_for :workouts
  root to: "stages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :stages
resources :workouts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stage.rb
class Stage < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workout.rb
class Workout < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :authenticate_user!
  def index
    @stages = current_user.stages
  end

  def show
  end

  def new
    @stage = current_user.stages.new
  end

  def create
    @stage = current_user.stages.new(allowed_params)
    if @stage.save
      redirect_to stages_path
    else
      render 'new'
    end
  end

  def edit
    @stage = current_user.stages.find(params[:id])
  end

  def update
    @stage = current_user.stages.find(params[:id])
    if @stage.update_attributes(allowed_params)
      redirect_to stages_path
    else
      render 'edit'
    end
  end

  def destroy
    @stage = current_user.stages.find(params[:id])
    @stage.destroy
    redirect_to stages_path
  end

  private
    def allowed_params
      params.require(:stage).permit(:weight, :height, :neck, :shoulders, :chest, :biceps, :waist, :hips, :thighs)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!
  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(allowed_params)

    if @workout.save
      redirect_to workouts_path
    else
      render 'new'
    end
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    if @workout.update_attributes(allowed_params)
      redirect_to workouts_path
    else
      render 'new'
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy
    redirect_to workouts_path
  end

  private
 def allowed_params
     params.require(:workout).permit(:id, :name)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Health</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'HEALTH', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Tracker', root_path %></li>
        <li><%= link_to 'Workouts', workouts_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.email %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/stages/edit.html.erb
<h1>Edit</h1>
<h3 style="background-color: #4CAF60; height: 70px; padding: 20px;">Here you can edit your selected Weigh In.</h3>

<% @stage.created_at %>
<div class="first">
  <%= form_for @stage do |s| %>

  <%= s.label :weight %> <br>
  <%= s.text_field :weight %> lbs. <br><br>

  <%= s.label :height %> <br>
  <%= s.text_field :height %> feet.<br><br>

  <%= s.label :neck %> <br>
  <%= s.text_field :neck %> inches.<br><br>

  <%= s.label :shoulders %> <br>
  <%= s.text_field :shoulders %> inches.<br><br>

  <%= s.label :chest %> <br>
  <%= s.text_field :chest %> inches.<br><br>
</div>
<div class="second">
  <%= s.label :biceps %> <br>
  <%= s.text_field :biceps %> inches.<br><br>

  <%= s.label :waist %> <br>
  <%= s.text_field :waist %> inches.<br><br>

  <%= s.label :hips %> <br>
  <%= s.text_field :hips %> inches.<br><br>

  <%= s.label :thighs %> <br>
  <%= s.text_field :thighs %> inches.<br><br>
</div>


<div class="save">
  <%= s.submit 'Save Details' %>
  <%= button_to 'All Records', stages_path, :method => :get %>

  <% end %>
</div>

app/views/stages/index.html.erb
<h1>Here's your record of each stage you've weighed in.</h1>
<h6><small>Every two weeks, remeasure and see what progress you've made.</small></h6>

<nav>
  <%= button_to 'Update', new_stage_path, :method => :get %>
</nav>

<% @stages.each do |stage| %>

<table>
  <thead>
      <tr>
        <th>Date</th>
        <th>Weight</th>
        <th>Height</th>
        <th>Neck</th>
        <th>Shoulders</th>
        <th>Chest</th>
        <th>Biceps</th>
        <th>Waist</th>
        <th>Hips</th>
        <th>Thighs</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= stage.created_at.strftime("%b %d, %Y") %></td>
        <td><%= stage.weight %> lbs.</td>
        <td><%= stage.height %> ft. </td>
        <td><%= stage.neck %> in.</td>
        <td><%= stage.shoulders %> in.</td>
        <td><%= stage.chest %> in.</td>
        <td><%= stage.biceps %> in.</td>
        <td><%= stage.waist %> in.</td>
        <td><%= stage.hips %> in.</td>
        <td><%= stage.thighs %> in.</td>
      </tr>
    </tbody>
</table>
<div class="delete">
  <%= button_to 'Delete', stage, :method => :delete %>
</div>
<div class="edit">
  <%= button_to 'Edit', edit_stage_path(stage), :method => :get %>
</div>
<% end %>

app/views/stages/new.html.erb
<h1>Weigh-In</h1>
<h3 style="background-color: #4CAF60; height: 70px; padding: 20px;">Now that you've signed up, Add your current information below.</h3>

<%= @stage.created_at %>

<%= form_for @stage do |s| %>

<%= s.label :weight %> <br>
<%= s.text_field :weight %> lbs. <br><br>

<%= s.label :height %> <br>
<%= s.text_field :height %> feet.<br><br>

<%= s.label :neck %> <br>
<%= s.text_field :neck %> inches.<br><br>

<%= s.label :shoulders %> <br>
<%= s.text_field :shoulders %> inches.<br><br>

<%= s.label :chest %> <br>
<%= s.text_field :chest %> inches.<br><br>

<%= s.label :biceps %> <br>
<%= s.text_field :biceps %> inches.<br><br>

<%= s.label :waist %> <br>
<%= s.text_field :waist %> inches.<br><br>

<%= s.label :hips %> <br>
<%= s.text_field :hips %> inches.<br><br>

<%= s.label :thighs %> <br>
<%= s.text_field :thighs %> inches.<br><br>

<%= s.submit 'Save Details' %>
<%= button_to 'All Records', stages_path, :method => :get %>

<% end %>

app/views/workouts/index.html.erb
<h1>Here are all your workouts!</h1>

<%= button_to 'Update', new_workout_path, :method => :get %>

<% @workouts.each do |workout| %>
<table class="workouts">
  <thead>
      <tr>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= link_to workout.name, workout, method: :get %></td>
      </tr>
    </tbody>
</table>

<%= button_to 'Delete', workout, method: :delete %>
<% end %>

app/views/workouts/new.html.erb
<h1>Workout</h1>
<h3 style="background-color: #4CAF60; height: 70px; padding: 20px;"> Add the name of your workout below.</h3>


<%= form_for @workout do |s| %>

<%= s.label :name %> <br>
<%= s.text_field :name %><br><br>

<%= s.submit 'Save Details' %>
<%= button_to 'All Records', stages_path, :method => :get %>

<% end %>

app/views/workouts/show.html.erb
<%= @workout.name %>